---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      # renovate: datasource=helm depName=intel-device-plugins-operator repository=https://intel.github.io/helm-charts/
      version: "0.36.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
