---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/namespace_v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
