---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}-nfs"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: "${NFS_VOLUME_CAPACITY:=5Gi}"
