---
connect:
  credentialsName: onepassword-connect-secrets
  api:
    resources:
      requests:
        cpu: 30m
        memory: 100Mi
      limits:
        memory: 100Mi
    logLevel: warn
  sync:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    logLevel: warn
