---
args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
  - --kubelet-request-timeout=10s
  - --metric-resolution=30s
metrics:
  enabled: true
serviceMonitor:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 200Mi
