---
controller:
  logLevel: info
  leaderElection:
    enabled: true

notification:
  enabled: true
  secretName: tuppr-notification-secret

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

silences:
  enabled: true
  alertmanager:
    address: http://kube-prometheus-stack-alertmanager.observability.svc:9093

monitoring:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
  dashboards:
    enabled: true
    grafanaOperator:
      enabled: true
      matchLabels:
        dashboards: grafana
