---
# yaml-language-server: $schema=https://schemas.clustrs.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: truenas-node-exporter
spec:
  scrapeInterval: 30s
  staticConfigs:
    - labels:
        instance: truenas
        job: truenas-node-exporter
      targets:
        - "${NAS_LAN_HOST}:9100"
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: truenas-smartctl-exporter
spec:
  scrapeInterval: 60s
  scrapeTimeout: 30s
  staticConfigs:
    - labels:
        instance: truenas
        job: truenas-smartctl-exporter
      targets:
        - "${NAS_LAN_HOST}:9633"
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: truenas-doco-cd
spec:
  scrapeInterval: 60s
  staticConfigs:
    - labels:
        instance: truenas
        job: truenas-doco-cd
      targets:
        - "${NAS_LAN_HOST}:9120"
