---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "bootstrap/**/*"
area/devops:
  - changed-files:
      - any-glob-to-any-file:
          - ".agents/**/*"
          - ".github/**/*"
          - ".justfile"
          - ".lefthook.yaml"
          - ".mise/**/*"
          - ".renovate/**/*"
          - ".renovaterc.json5"
          - ".vscode/**/*"
          - "ansible/**/*"
          - "mod.just"
area/docker:
  - changed-files:
      - any-glob-to-any-file: "docker/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"
          - "README.md"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**/*"
namespace/media:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/media/**/*"
namespace/downloads:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/downloads/**/*"
area/scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**/*"
area/talos:
  - changed-files:
      - any-glob-to-any-file: "talos/**/*"
