---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dragonfly-secret
    template:
      engineVersion: v2
      data:
        password: "{{ .DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: dragonfly
      rewrite:
        - regexp:
            source: (.*)
            target: DRAGONFLY_$1
