---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vwn-app-tls
spec:
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          property: tls.crt
          remoteKey: vwn-app-tls
    - match:
        secretKey: tls.key
        remoteRef:
          property: tls.key
          remoteKey: vwn-app-tls
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: vwn-app-tls
  updatePolicy: Replace
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vwn-casa-tls
spec:
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          property: tls.crt
          remoteKey: vwn-casa-tls
    - match:
        secretKey: tls.key
        remoteRef:
          property: tls.key
          remoteKey: vwn-casa-tls
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: vwn-casa-tls
  updatePolicy: Replace
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cluster-vwn-io-tls
spec:
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          property: tls.crt
          remoteKey: cluster-vwn-io-tls
    - match:
        secretKey: tls.key
        remoteRef:
          property: tls.key
          remoteKey: cluster-vwn-io-tls
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: cluster-vwn-io-tls
  updatePolicy: Replace
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: apps-vwn-io-tls
spec:
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          property: tls.crt
          remoteKey: apps-vwn-io-tls
    - match:
        secretKey: tls.key
        remoteRef:
          property: tls.key
          remoteKey: apps-vwn-io-tls
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: apps-vwn-io-tls
  updatePolicy: Replace
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vwn-io-tls
spec:
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          property: tls.crt
          remoteKey: vwn-io-tls
    - match:
        secretKey: tls.key
        remoteRef:
          property: tls.key
          remoteKey: vwn-io-tls
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: vwn-io-tls
  updatePolicy: Replace
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: clustrs-dev-tls
spec:
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          property: tls.crt
          remoteKey: clustrs-dev-tls
    - match:
        secretKey: tls.key
        remoteRef:
          property: tls.key
          remoteKey: clustrs-dev-tls
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: clustrs-dev-tls
  updatePolicy: Replace
