---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-db
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-db-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .OPENWEBUI_DB_USER }}"
        password: "{{ .OPENWEBUI_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: open-webui
      rewrite:
        - regexp:
            source: (.*)
            target: OPENWEBUI_$1
