---
# yaml-language-server: $schema=https://schemas.clustrs.dev/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
  namespace: system-upgrade
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.37.1
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      description: no kopiur backup is running
      expr: status.phase != 'Running'
      timeout: 30m
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      description: no kopiur restore is running
      expr: "!(status.phase in ['Resolving', 'Restoring'])"
