---
# yaml-language-server: $schema=https://schemas.clustrs.dev/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: cluster
  namespace: system-upgrade
spec:
  talos:
    # renovate: datasource=custom.talos-factory depName=siderolabs/talos
    version: v1.14.1
  policy:
    rebootMode: default
    placement: hard
    waitForVolumeDetach: true
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      description: no kopiur backup is running
      expr: status.phase != 'Running'
      timeout: 30m
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      description: no kopiur restore is running
      expr: "!(status.phase in ['Resolving', 'Restoring'])"
      timeout: 30m
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
      timeout: 30m
  parallelism: 1
  silences:
    - matchers:
        - name: alertname
          matchType: "=~"
          value: KubeNodeNotReady|KubeNodeUnreachable|KubeNodeReadinessFlapping|KubeNodeEviction|KubeletDown
      maxDuration: 4h
    - matchers:
        - name: alertname
          matchType: "=~"
          value: KubeDeploymentReplicasMismatch|KubeDaemonSetNotScheduled|KubeDaemonSetRolloutStuck|KubeContainerWaiting|KubePodNotReady|KubePdbNotEnoughHealthyPods
      maxDuration: 4h
    - matchers:
        - name: alertname
          matchType: "=~"
          value: CephOSDDown|CephOSDHostDown|CephMonDown|CephHealthWarning|CephOSDFlapping|CephDaemonSlowOps|CephNodeNetworkPacketDrops|CephMonDownQuorumAtRisk|CephOSDDownHigh
      maxDuration: 4h
    - matchers:
        - name: alertname
          value: UpgradeJobRunningTooLong
      maxDuration: 4h
