---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword-github
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          key: token
          name: onepassword-github-sa
      vault: GitHub
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-github-sa
spec:
  data:
    - secretKey: token
      remoteRef:
        key: onepassword-github-cluster-sa
        property: OP_SERVICE_ACCOUNT_TOKEN
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-github-sa
