---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
  labels:
    crds.flux.home.arpa/disabled: "true"
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns-cloudflare
  interval: 1h
  values:
    domainFilters:
      - "${DOMAIN_APP}"
      - "${DOMAIN_CASA}"
      - "${DOMAIN_IO}"
      - "${DOMAIN_PROXII}"
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: CF_API_TOKEN
            name: external-dns-cloudflare-secret
    excludeDomains:
      - "${DOMAIN_APPS}"
      - "${DOMAIN_CLUSTER}"
      - "home.${DOMAIN_IO}"
      - "iot.${DOMAIN_IO}"
      - "internal.${DOMAIN_PROXII}"
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external
    fullnameOverride: *app
    policy: sync
    provider: cloudflare
    resources:
      requests:
        cpu: 15m
        memory: 64Mi
      limits:
        memory: 64Mi
    serviceMonitor:
      enabled: true
    sources:
      - gateway-httproute
      - crd
    triggerLoopOnEvent: true
    txtOwnerId: k8s
    txtPrefix: "k8s."
