---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: firefly-iii-secret
    template:
      data:
        APP_KEY: "{{ .FIREFLY_APP_KEY }}"
        SITE_OWNER: "{{ .FIREFLY_SITE_OWNER }}"
        STATIC_CRON_TOKEN: "{{ .FIREFLY_STATIC_CRON_TOKEN }}"
      engineVersion: v2
  dataFrom:
    - extract:
        key: firefly-III
      rewrite:
        - regexp:
            source: (.*)
            target: FIREFLY_$1
