---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/replacements.yaml
resources:
  - ./prowlarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./configarr/ks.yaml
