---
networks:
  apps:
    external: true
services:
  hermes:
    command: gateway run
    container_name: hermes
    environment:
      API_SERVER_CORS_ORIGINS: https://hermes.vwn.app
      API_SERVER_ENABLED: "true"
      API_SERVER_HOST: 0.0.0.0
      API_SERVER_KEY: ${HERMES_API_SERVER_KEY}
      HERMES_DASHBOARD: "1"
      HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ${HERMES_DASHBOARD_PASSWORD}
      HERMES_DASHBOARD_BASIC_AUTH_SECRET: ${HERMES_DASHBOARD_SECRET}
      HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ${HERMES_DASHBOARD_USERNAME}
      HERMES_TIMEZONE: Europe/Amsterdam
    image: docker.io/nousresearch/hermes-agent:v2026.9.24@sha256:fca358f12efd65bfaaca05884166f15c0e2788375ca30d77061ac1ebc96452b7
    labels:
      dexd.enabled: "true"
      traefik.enable: "true"
      traefik.http.routers.hermes-api.entrypoints: websecure
      traefik.http.routers.hermes-api.rule: Host(`hermes-api.vwn.app`)
      traefik.http.routers.hermes-api.service: hermes-api
      traefik.http.routers.hermes.entrypoints: websecure
      traefik.http.routers.hermes.rule: Host(`hermes.vwn.app`)
      traefik.http.routers.hermes.service: hermes
      traefik.http.services.hermes-api.loadbalancer.server.port: "8642"
      traefik.http.services.hermes.loadbalancer.server.port: "9119"
    networks:
      - apps
    restart: unless-stopped
    volumes:
      - data:/opt/data
volumes:
  data: {}
