---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii-importer
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: firefly-iii-importer-secret
    template:
      engineVersion: v2
      data:
        FIREFLY_III_ACCESS_TOKEN: "{{ .FIREFLY_III_ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: firefly-III
