---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-secret
    template:
      data:
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        GF_SECURITY_ADMIN_USER: admin
      engineVersion: v2
  dataFrom:
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: (.*)
            target: GRAFANA_$1
