---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: wan-failover
  annotations:
    external-dns.kubernetes.io/hostname: "wan-failover.${DOMAIN_CLUSTER}"
spec:
  externalName: "${WAN_FAILOVER_HOST}"
  type: ExternalName
