---
# yaml-language-server: $schema=https://schemas.clustrs.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: printer
spec:
  endpoints:
    - dnsName: "printer.iot.home.${DOMAIN_IO}"
      recordType: A
      targets:
        - "${PRINTER_IOT_HOST}"
    - dnsName: "canon.iot.${DOMAIN_IO}"
      recordType: A
      targets:
        - "${PRINTER_IOT_HOST}"
