---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: longhorn-values
    namespace: longhorn-system
    files:
      - values.yaml=./helm/values.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
resources:
  - ./namespace.yaml
  - ./helmrelease.yaml
  - ./node-configs/talos-cp-01.yaml
  - ./node-configs/talos-cp-02.yaml
  - ./node-configs/talos-cp-03.yaml
