---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}
  # weatherapi: weatherapiapikey

title: Home Lab

background: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
backgroundOpacity: 0.5

theme: dark
color: slate
headerStyle: underlined

maxGroupColumns: 6
maxBookmarkGroupColumns: 4
useEqualHeights: false
statusStyle: dot
fullWidth: false
layout:
  Home Automation:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 4
  RowA:
    style: row
    columns: 5
    header: false
    useEqualHeights: true
    Observability: {}
    Storage: {}
    Documents: {}
    Database: {}
    Development: {}
  RowB:
    style: row
    columns: 5
    header: false
    useEqualHeights: true
    AI: {}
    Automation: {}
    Finance: {}
  RowC:
    header: false
    useEqualHeights: true
    Bookmarks:
      style: row
      columns: 2

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: true
  provider: custom
  url: https://kagi.com/search?token={{HOMEPAGE_VAR_KAGI_SESSION_TOKEN}}&q=
  suggestionUrl: https://kagi.com/api/autosuggest?token={{HOMEPAGE_VAR_KAGI_SESSION_TOKEN}}&q=
  target: _blank
