---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}
  # weatherapi: weatherapiapikey

title: Home Lab

background: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
backgroundOpacity: 0.5

theme: dark
color: slate
headerStyle: underlined

useEqualHeights: true
statusStyle: dot
layout:
  Observability:
    style: row
    columns: 4
  Storage:
    style: row
    columns: 4
  Database:
    style: row
    columns: 4
  Automation:
    style: row
    columns: 4
  Network:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 3

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: true
  provider: custom
  url: https://kagi.com/search?token={{HOMEPAGE_VAR_KAGI_SESSION_TOKEN}}&q=
  suggestionUrl: https://kagi.com/api/autosuggest?token={{HOMEPAGE_VAR_KAGI_SESSION_TOKEN}}&q=
  target: _blank
