---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-secret
    template:
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        N8N_RUNNERS_AUTH_TOKEN: "{{ .N8N_RUNNERS_AUTH_TOKEN }}"
  dataFrom:
    - extract:
        key: n8n
      rewrite:
        - regexp:
            source: (.*)
            target: N8N_$1
