---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuppr-notification
  namespace: system-upgrade
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tuppr-notification-secret
    template:
      data:
        url: "pover://{{ .ALERTMANAGER_PUSHOVER_USER_KEY }}@{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: alertmanager
      rewrite:
        - regexp:
            source: (.*)
            target: ALERTMANAGER_$1
