---
# yaml-language-server: $schema=https://schemas.clustrs.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  datasource:
    access: proxy
    isDefault: true
    name: Prometheus
    type: prometheus
    url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
  instanceSelector:
    matchLabels:
      dashboards: grafana
  uid: prometheus
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  datasource:
    access: proxy
    jsonData:
      implementation: prometheus
    name: Alertmanager
    type: alertmanager
    url: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093
  instanceSelector:
    matchLabels:
      dashboards: grafana
  uid: alertmanager
