frr version 10.7
frr defaults traditional
hostname nas-frr
log stdout
no ipv6 forwarding

router bgp 64515
 bgp router-id 10.10.0.41

 no bgp ebgp-requires-policy
 bgp network import-check

 neighbor 10.10.0.1 remote-as 64513

 address-family ipv4 unicast
  network 10.10.2.100/32
 exit-address-family
exit
