---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/cluster-settings
namespace: default
resources:
  - ./namespace.yaml
  - ./firefly/ks.yaml
  - ./firefly-importer/ks.yaml
  - ./forgejo/ks.yaml
  - ./homepage/ks.yaml
  - ./paperless/ks.yaml
  - ./unifi-voucher-site/ks.yaml
