---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-voucher-site
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-voucher-site-secret
    template:
      data:
        UNIFI_IP: '{{ .UNIFI_HOST | trimPrefix "https://" | trimPrefix "http://" | trimSuffix "/" }}'
        UNIFI_PORT: "443"
        UNIFI_TOKEN: "{{ .UNIFI_API_KEY }}"
  dataFrom:
    - extract:
        key: unifi
      rewrite:
        - regexp:
            source: (.*)
            target: UNIFI_$1
