---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-voucher-site
spec:
  chartRef:
    kind: OCIRepository
    name: unifi-voucher-site
  interval: 1h
  driftDetection:
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    defaultPodOptions:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/glenndehaan/unifi-voucher-site
              tag: 8.13.1@sha256:3d6a371292a50922b7920ea632eaddd16f438d822e5258d6c4e5a2ea9be9558e
            env:
              AUTH_DISABLE: "true"
              LOG_LEVEL: info
              TZ: "${CLUSTER_TIMEZONE}"
              UNIFI_SITE_ID: default
            envFrom:
              - secretRef:
                  name: unifi-voucher-site-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        ports:
          http:
            port: *port
