---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  dependsOn: []
  interval: 1h
  values:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    gitea:
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__NAME
          valueFrom:
            secretKeyRef:
              key: dbname
              name: forgejo-postgres-app
        - name: GITEA__DATABASE__USER
          valueFrom:
            secretKeyRef:
              key: username
              name: forgejo-postgres-app
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              key: password
              name: forgejo-postgres-app
      admin:
        existingSecret: forgejo-admin-secret
      config:
        database:
          DB_TYPE: postgres
          HOST: "${APP}-postgres-rw:5432"
        server:
          DOMAIN: forgejo.${DOMAIN_CLUSTER}
          ROOT_URL: https://forgejo.${DOMAIN_CLUSTER}
          SSH_DOMAIN: forgejo.${DOMAIN_CLUSTER}
    httpRoute:
      enabled: false
    persistence:
      storageClass: ceph-block
    tcpRoute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: ssh
