---
# yaml-language-server: $schema=https://schemas.clustrs.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=code.forgejo.org/forgejo-helm/forgejo
    tag: "17.1.7"
  url: oci://code.forgejo.org/forgejo-helm/forgejo
