---
# yaml-language-server: $schema=https://schemas.clustrs.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
  namespace: network
  labels:
    external-dns.home.arpa/public-only: "true"
spec:
  endpoints:
    - dnsName: "external.${DOMAIN_PROXII}"
      recordType: CNAME
      targets:
        - "${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
