---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: configarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: configarr
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 4000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 4000
        runAsNonRoot: true
        runAsUser: 4000
    controllers:
      configarr:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          failedJobsHistory: 1
          schedule: "0 0/12 * * *"
          successfulJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/raydak-labs/configarr
              tag: 1.34.0@sha256:738f79088c08ccaf578e71ca44faca16181d5399934beedbb81851a4f9ba06c1
            envFrom:
              - secretRef:
                  name: configarr-secret
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
    persistence:
      config:
        type: configMap
        name: configarr-config
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
            readOnly: true
      repos:
        type: emptyDir
        globalMounts:
          - path: /app/repos
