---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudnative-pg-storj
spec:
  configuration:
    destinationPath: "s3://cloudnative-pg"
    endpointURL: "https://gateway.storjshare.io"
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: CNPG_S3_ACCESS_KEY
      secretAccessKey:
        name: cloudnative-pg-secret
        key: CNPG_S3_SECRET_KEY
  retentionPolicy: 30d
