---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
spec:
  chartRef:
    kind: OCIRepository
    name: paperless-ngx
  interval: 1h
  dependsOn: []
  driftDetection:
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
    controllers:
      paperless-ngx:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 3.0.5@sha256:65a4cabf0169ea7fbd90ab7bb28ba3f8b5909613635acda1a03ad606f34b456b
            env:
              PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
              PAPERLESS_CONSUMER_POLLING_INTERVAL: "15"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              PAPERLESS_CONSUMPTION_DIR: &consumePath /mnt/archive/consume
              PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.${DOMAIN_CLUSTER}"
              PAPERLESS_DATA_DIR: &dataPath /usr/src/paperless/data
              PAPERLESS_DBENGINE: postgresql
              PAPERLESS_DBHOST: "${APP}-postgres-rw"
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: paperless-ngx-postgres-app
              PAPERLESS_DBPORT: "5432"
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: paperless-ngx-postgres-app
              PAPERLESS_DISABLE_REGULAR_LOGIN: "false"
              PAPERLESS_EXPORT_DIR: &exportPath /mnt/archive/export
              PAPERLESS_FILENAME_FORMAT: >-
                {{"{{"}} created_year {{"}}"}}/{{"{{"}} correspondent {{"}}"}}/{{"{{"}} created {{"}}"}} - {{"{{"}} title {{"}}"}} - {{"{{"}} doc_pk {{"}}"}}
              PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: "true"
              PAPERLESS_MEDIA_ROOT: &mediaPath /mnt/archive/media
              PAPERLESS_OCR_LANGUAGE: nld+eng
              PAPERLESS_OCR_LANGUAGES: nld
              PAPERLESS_PORT: &port 8000
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: "false"
              PAPERLESS_REDIS: "redis://${APP}-dragonfly:6379"
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_TIKA_ENABLED: "1"
              PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
              PAPERLESS_TIME_ZONE: ${CLUSTER_TIMEZONE}
              PAPERLESS_TRUSTED_PROXIES: "**"
              PAPERLESS_URL: "https://paperless.${DOMAIN_CLUSTER}"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_WORKER_TIMEOUT: "14400"
              USERMAP_GID: "1000"
              USERMAP_UID: "1000"
            envFrom:
              - secretRef:
                  name: paperless-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 60
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: 250m
                memory: 2Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsGroup: 0
              runAsUser: 0
          gotenberg:
            image:
              repository: docker.io/gotenberg/gotenberg
              tag: 8.37.0@sha256:f29984bd1e226bf1b93ba90af06000afa8b315853e99d27b9aaa41b93f15c769
            args:
              - "gotenberg"
              - "--chromium-disable-javascript=true"
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
          tika:
            image:
              repository: docker.io/apache/tika
              tag: 3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 768Mi
    persistence:
      config:
        existingClaim: "${KOPIUR_CLAIM:=${APP}}"
        globalMounts:
          - path: *dataPath
      archive:
        existingClaim: "paperless-ngx-smb-archive"
        globalMounts:
          - path: *consumePath
            subPath: consume
          - path: *exportPath
            subPath: export
          - path: *mediaPath
            subPath: media
      backups:
        existingClaim: "paperless-ngx-smb-backup"
        globalMounts:
          - path: /mnt/backups
            subPath: Apps/Paperless
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /usr/src/paperless/data/log
            subPath: log
    service:
      app:
        controller: paperless-ngx
        ports:
          http:
            port: *port
