---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/persistentvolume_v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP}-smb-archive
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2T
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: smb-credentials
      namespace: system
    volumeAttributes:
      source: //${NAS_HOST}/Archive
    volumeHandle: ${APP}-smb-archive
  mountOptions:
    - noperm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/persistentvolume_v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP}-smb-backup
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2T
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: smb-credentials
      namespace: system
    volumeAttributes:
      source: //${NAS_HOST}/Backup
    volumeHandle: ${APP}-smb-backup
  mountOptions:
    - noperm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
