---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-smb-archive
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  storageClassName: smb
  volumeName: ${APP}-smb-archive
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-smb-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  storageClassName: smb
  volumeName: ${APP}-smb-backup
