---
# yaml-language-server: $schema=https://schemas.clustrs.dev/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${APP}-scaler
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 30
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: ${APP}
  triggers:
    - metadata:
        ignoreNullValues: "0"
        query: probe_success{instance="${NAS_HOST}:445"}
        serverAddress: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
        threshold: "1"
      type: prometheus
