---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: nas-lan
  annotations:
    external-dns.kubernetes.io/hostname: "nas.lan.home.${DOMAIN_IO}"
spec:
  externalName: "${NAS_LAN_HOST}"
  type: ExternalName
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: nas-iot
  annotations:
    external-dns.kubernetes.io/hostname: "nas.iot.home.${DOMAIN_IO}"
spec:
  externalName: "${NAS_IOT_HOST}"
  type: ExternalName
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: nas-storage
  annotations:
    external-dns.kubernetes.io/hostname: "nas.storage.home.${DOMAIN_IO}"
spec:
  externalName: "${NAS_HOST}"
  type: ExternalName
