---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  bootstrap:
    recovery:
      source: &archive ${APP}-backup-archive
      database: ${POSTGRES_DATABASE:=${APP}}
      owner: ${POSTGRES_USERNAME:=${APP}}
  enablePDB: ${POSTGRES_ENABLE_PDB:=false}
  enableSuperuserAccess: true
  externalClusters:
    - name: *archive
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: ${APP}-postgres-backup
          serverName: ${APP}
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-standard-trixie@sha256:58d19a1edb30d42fc2be3470ac7719caa496a4f3a7f1289472d6c3f6b04c8fd1
  instances: ${POSTGRES_INSTANCES:=1}
  maxSyncReplicas: ${POSTGRES_SYNC_REPLICAS:=0}
  minSyncReplicas: ${POSTGRES_SYNC_REPLICAS:=0}
  monitoring:
    enablePodMonitor: true
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: ${APP}-postgres-backup
        serverName: ${APP}
  postgresql:
    parameters:
      archive_timeout: 5min
      max_connections: "100"
  primaryUpdateStrategy: unsupervised
  resources:
    requests:
      memory: 256Mi
  storage:
    size: ${POSTGRES_STORAGE:=5Gi}
    storageClass: openebs-hostpath
