---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-postgres
spec:
  dataFrom:
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: (.*)
            target: CNPG_$1
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: *name
    template:
      data:
        S3_ACCESS_KEY: "{{ .CNPG_S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .CNPG_S3_SECRET_KEY }}"
      engineVersion: v2
