---
# yaml-language-server: $schema=https://schemas.clustrs.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ${APP}-postgres-backup
spec:
  configuration:
    data:
      compression: bzip2
      encryption: AES256
    destinationPath: "s3://vwn-io-cluster-cnpg/dedicated/${APP}"
    endpointURL: "https://s3.us-west-001.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        key: S3_ACCESS_KEY
        name: &secret ${APP}-postgres
      secretAccessKey:
        key: S3_SECRET_KEY
        name: *secret
    wal:
      compression: bzip2
      encryption: AES256
      maxParallel: 8
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  retentionPolicy: 14d
