---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph-operator
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /metadata/annotations/helm.sh~1resource-policy
                value: keep
            target:
              kind: CustomResourceDefinition
  values:
    crds:
      enabled: true
    image:
      repository: ghcr.io/rook/ceph
    csi:
      serviceMonitor:
        enabled: false
    cephCommandsTimeoutSeconds: "20"
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 80m
        memory: 256Mi
      limits:
        memory: 512Mi
