---
# yaml-language-server: $schema=https://schemas.clustrs.dev/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: truenas
spec:
  endpoints:
    - ip:
        address: "${NAS_LAN_HOST}"
        port: 8443
  tls:
    alpnProtocols:
      - http/1.1
    insecureSkipVerify: true
