---
# yaml-language-server: $schema=https://schemas.clustrs.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-logs
spec:
  datasource:
    access: proxy
    jsonData:
      maxLines: 1000
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    url: http://victoria-logs-server.observability.svc.cluster.local:9428
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: victoriametrics-logs-datasource
      version: 0.32.0
  uid: victoria-logs
