---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: victoria-logs-syslog
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "victorialogs-syslog.${DOMAIN_CLUSTER}"
spec:
  loadBalancerSourceRanges:
    - "${NAS_LAN_HOST}/32"
  ports:
    - name: syslog-tcp
      port: 514
      protocol: TCP
      targetPort: syslog-tcp
  selector:
    app: server
    app.kubernetes.io/instance: victoria-logs
    app.kubernetes.io/name: victoria-logs-single
  type: LoadBalancer
