---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: csi-driver-smb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smb-credentials
    template:
      data:
        username: "{{ .USERNAME }}"
        password: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: smb-credentials
