---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smb-credentials
    creationPolicy: Owner
    template:
      data:
        password: "{{ .SMB_PASSWORD }}"
        username: "{{ .SMB_USERNAME }}"
      engineVersion: v2
  dataFrom:
    - extract:
        key: smb-credentials
      rewrite:
        - regexp:
            source: (.*)
            target: SMB_$1
