---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  interval: 1h
  dependsOn:
    - name: rook-ceph-operator
    - name: ceph-csi-drivers
  values:
    operatorNamespace: rook-ceph
    cephImage:
      repository: quay.io/ceph/ceph
      tag: v20.2.4
    monitoring:
      enabled: true
      createPrometheusRules: true
      prometheusRuleOverrides:
        CephNodeDiskspaceWarning:
          for: 5m
          expr: |
            predict_linear(node_filesystem_free_bytes{device=~"/.*"}[2d], 3600 * 24 * 5)
              * on(cluster, instance) group_left(nodename) node_uname_info < 0
            and on(instance) (time() - node_boot_time_seconds > 1800)
        CephNodeNetworkPacketDrops:
          for: 1m
    toolbox:
      enabled: true
    cephClusterSpec:
      cleanupPolicy:
        wipeDevicesFromOtherClusters: true
      cephConfig:
        global:
          bdev_enable_discard: "true"
          bdev_async_discard_threads: "1"
          mon_data_avail_warn: "10"
        mon:
          mon_cluster_log_to_stderr: "false"
        osd:
          ms_async_op_threads: "5"
          bluestore_rocksdb_options_annex: "stats_dump_period_sec=0"
        mgr:
          mgr/pg_autoscaler/log_level: "error"
      crashCollector:
        disable: false
      csi:
        readAffinity:
          enabled: true
      dashboard:
        enabled: true
        ssl: false
        prometheusEndpoint: http://prometheus-operated.observability.svc.cluster.local:9090
      healthCheck:
        muteHealthWarning:
          AUTH_INSECURE_ROTATING_SERVICE_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_CLIENT_KEY_TYPE:
            policy: mute
          AUTH_INSECURE_KEYS_ALLOWED:
            policy: mute
          AUTH_INSECURE_KEYS_CREATABLE:
            policy: mute
      mgr:
        modules:
          - name: rook
            enabled: false
          - name: restful
            enabled: false
          - name: pg_autoscaler
            enabled: true
      network:
        provider: host
        addressRanges:
          public:
            - 10.200.0.0/24
          cluster:
            - 10.200.0.0/24
      placement:
        all:
          tolerations:
            - key: tuppr.home-operations.com/outdated
              operator: Exists
        osd:
          tolerations:
            - key: tuppr.home-operations.com/outdated
              operator: Exists
              effect: PreferNoSchedule
      security:
        cephx:
          daemon:
            keyRotationPolicy: KeyGeneration
            keyGeneration: 2
          csi:
            keyType: aes
      resources:
        mgr:
          requests:
            cpu: 60m
            memory: 512Mi
          limits:
            memory: 1280Mi
        mon:
          requests:
            cpu: 60m
            memory: 512Mi
          limits:
            memory: 1Gi
        osd:
          requests:
            cpu: 150m
            memory: 2Gi
          limits:
            memory: 4Gi
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "2"
        nodes:
          - name: talos-cp-01
            devices:
              - name: /dev/disk/by-id/nvme-CT2000T500SSD8_2545543A2190
          - name: talos-cp-02
            devices:
              - name: /dev/disk/by-id/nvme-CT2000T500SSD8_25405348D601
          - name: talos-cp-03
            devices:
              - name: /dev/disk/by-id/nvme-CT2000T500SSD8_254053487747
          - name: talos-worker-01
            devices:
              - name: /dev/disk/by-id/nvme-CT2000P310SSD8_252450B1A33B
          - name: talos-worker-02
            devices:
              - name: /dev/disk/by-id/nvme-CT2000T500SSD8_2545542DA3BA
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          # parameters:
          #   compression_algorithm: zstd
          #   compression_mode: aggressive
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          mountOptions: ["discard"]
          parameters:
            imageFormat: "2"
            imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: ceph-block-snapshot
      isDefault: false
      deletionPolicy: Delete
    cephFileSystems: []
    cephObjectStores: []
