---
alertmanager:
  alertmanagerSpec:
    alertmanagerConfiguration:
      name: alertmanager
    podAntiAffinity: soft
    replicas: 3
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
          storageClassName: ceph-block
crds:
  enabled: true
  upgradeJob:
    enabled: true
grafana:
  enabled: false
  forceDeployDashboards: true
  operator:
    dashboardsConfigMapRefEnabled: true
    folder: observability
    matchLabels:
      dashboards: grafana
kubeEtcd:
  service:
    selector:
      component: kube-apiserver
kubeProxy:
  enabled: false
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi
    retention: 30d
    retentionSize: 40GB
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 60Gi
          storageClassName: ceph-block
