---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/namespace
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
          pod-security.kubernetes.io/audit: privileged
replacements:
  - path: ../../components/replacements/replacements.yaml
resources:
  - ./kube-prometheus-stack/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./silence-operator/ks.yaml
  - ./grafana-operator/ks.yaml
  - ./unpoller/ks.yaml
  - ./blackbox-exporter/ks.yaml
