apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
stringData:
  CLUSTER_ACME_EMAIL: ENC[AES256_GCM,data:i+1O1xU/2etRyzp6eZ1NHC4ii7GD,iv:H6TWiLvujrpDK+HYk0ztnTCmMzYrTiTCPDwHmV3LrPA=,tag:kcEX/cGd2z91pFZPwe9v8A==,type:str]
  DOMAIN_IO: ENC[AES256_GCM,data:yfNh23D4,iv:iWbdb4C6XdPw173BVe5SrsIUhtKU17iNIJYKTB9hJUY=,tag:Xt48Rj4ECJeOL4ZZdDlXOA==,type:str]
  DOMAIN_APP: ENC[AES256_GCM,data:+7O5L+o5ww==,iv:aMxJ+Lv0vAxoNEURPYQPoWwP6on70B17SCAyHgyHlTE=,tag:L1s32hknc99yUqlZegSi3A==,type:str]
  DOMAIN_CASA: ENC[AES256_GCM,data:NBhg9r6DAfc=,iv:5wpLBJrfVamCpipANcTt4OeEq3/VmuagYrkOPjeBYY8=,tag:X+Betci7X92oobsaEwMR6A==,type:str]
  DOMAIN_PROXII: ENC[AES256_GCM,data:KbHhvQRitt/i,iv:n7qCnPs2PJz2zYvA+QUCFzB7aKq7Tw5lQXtxv3G+jY0=,tag:SdTALcrwUIC6TQ2SVe1Thw==,type:str]
  #ENC[AES256_GCM,data:F8gkCc5NFXfSFGAml7JvK6dHtSVhjV7It8HmWNRBYGz16TEsNncejo4kWOIMzGbvixo=,iv:XE3plJCUG+R+3xcmwyFAscbf7aCAu/dTAD8vHwwc1ho=,tag:yZGhJvunxEPcHgEc+2n1Pw==,type:comment]
  DOMAIN_CLUSTER: ENC[AES256_GCM,data:pzJulZl6rHOdvjqhups=,iv:Sn2vgW1dHfAYyZo1BwPWMVO5PwbiLxjSKvZQ34Fxjv4=,tag:3LNTvG7ih7P0QefoWsZ6xg==,type:str]
  #ENC[AES256_GCM,data:eAQKR2149k+T2wbFc4yQqPMnFnCfmZ8OuzK+jFI1,iv:s7eKXHCrSgU3tXozsZ7Z4gslIhGz2FXHdN1lWdwN4gA=,tag:U29vKxptlb+VfV02cwzHLQ==,type:comment]
  DOMAIN_APPS: ENC[AES256_GCM,data:AhE8ip1glxd8n/A=,iv:NwEn2SXTcjlXwlbQoYMRF0D6eVZWgf5Z2KLamhNnWog=,tag:uJ7OgaJzWhxju44mCe0EyA==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:beRU3Wu+1fguP/ocztQodvvb79PL8objDV+Lvs6dCBAFg5Ld,iv:TMSWZp+t3w3/CXKXck+pIuoAwPRFlqN/G0iyH6mg684=,tag:J+UvYZqMmXNClHYGzbBAlw==,type:str]
  PG_HOST: ENC[AES256_GCM,data:Z4Y1ZX10bm7E5c5HMbwORBHcwOHepf8/at0o4d4maDEr+QF7YShXorba,iv:1bcrhpNS361SPIfJ9qeJSTiGe9/9MYXf248d1M/7qWk=,tag:q7WyCGDulyOjkeiA35VZjw==,type:str]
  DRAGONFLY_HOST: ENC[AES256_GCM,data:BLgLJG10N/3QGqC7Yu0eIcwGZeFmqX10t+/I+7+ckKQI3CsP,iv:lzOpBXGz/dyNKClJoYaa6RVylmhJHo3gsPq17uR6pVE=,tag:0swgqG6wcJUd+Z3Ulw8b+A==,type:str]
  HOME_ASSISTANT_LAN_HOST: ENC[AES256_GCM,data:q4XDxN928Fv17w==,iv:5EirLorC3HHSlh2fYeEUZTN61y03w7+BZGgcwvbWHhA=,tag:FOqKlSMuJPaA3fGxt6OlpQ==,type:str]
  HOME_ASSISTANT_IOT_HOST: ENC[AES256_GCM,data:ZTcXP8Ol/MnpJA==,iv:9Nz+qJwnTs0urYqPsy9b5WlzstNTbi8Yv9OMJqgSkGY=,tag:Hfrfjm113bBMUPUTEd3QuA==,type:str]
  NAS_HOST: ENC[AES256_GCM,data:6pxB7i1mhSB053A=,iv:5bySB2quQjWGaX+KFeWNgnvbrli0p0iwKvjxdINyH4w=,tag:l7NCLYOUodmbvuOV3bcNmA==,type:str]
  NAS_LAN_HOST: ENC[AES256_GCM,data:JVogAxE3qIZlPw==,iv:AsiCJ9hIdofL+hLhrEE/zazRGT8CxvT1Hw3afPWjKNo=,tag:iYHsTU+a1IyjcM8gY06Z7Q==,type:str]
  LAN_SUBNET: ENC[AES256_GCM,data:09bNZrXVlnVjZlzj,iv:iHHsZr7U7dqfqklf24FQ4CY3m6X3rpwR4bRIngFDTFE=,tag:0uZWvz7fUbgQPZRUMfnpxw==,type:str]
  IOT_SUBNET: ENC[AES256_GCM,data:H7UUowRwLI2M4OeM,iv:pkRTTk/emR+imKtw6cdElMWzj5RpoWXZnm61xbCOEiU=,tag:sf1t1sff0AZmhgwbL87qBg==,type:str]
  WAN_FAILOVER_HOST: ENC[AES256_GCM,data:n68ro+lVobDAT0k=,iv:A215jrPWiVVAcFwJ6IE+uIovy9oezA6kqZ384P3utjo=,tag:Omtjr9rRUIcrNe4rMOlJTA==,type:str]
  ANNA_IOT_HOST: ENC[AES256_GCM,data:0AWkGLe277O2Og==,iv:z50QAx1f04oNgl8upc3hPpjEtFonePMaFNpWOpXRdrU=,tag:k8HhrdCmQOdeWlK93KP6hA==,type:str]
  ADAM_IOT_HOST: ENC[AES256_GCM,data:TTDBTLMaIHybwg==,iv:3UkHJqp5OUQdKDUIp5OuyePLdZfnrH/n6MctIUecOF8=,tag:X6pkRdUcCk+w7tRzuRfIHw==,type:str]
  PRINTER_IOT_HOST: ENC[AES256_GCM,data:T3j2rJUgnhtJLA==,iv:fpABs1i7vHyOOwtx/5Fi5YSiONBpdWMyCEiicJNxSk4=,tag:aauiqKuqA+YgzMAvqfVe4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVElCVEZhZ3MzUGk4THls
        MmJYVkVtNEgzN1ZSaExES0h6MVZSeDUvRlZNCklQMmU2NlpQd2tmODBrTGxsU0sx
        NlVzT1g1SHFNcWpRTnFibWwvcXdXbjQKLS0tIHk0d1F3RzVLTVowSk9BU2F5eDF0
        OFZMWEx0aFc2M1FyWDhLblNmSUNTRVUKUtYfYzzNkP6wbC2yDJKmguBNJOqtf0C3
        V/dSkTyoXzayJyFcEW+1m8fvo2V0I8x7PYXG7NhyDjZQYtUm/G7waA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8a4krypwu2xwdc8wgsmvpxru0dwaayk9njcevy9ddzw6kwvcaks7wzhv5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T10:00:03Z"
  mac: ENC[AES256_GCM,data:4lU5koaU8roKetoZ21mSBt6ezdxWbTogeKxvt41R8bEvm1dktfqvsZRipicW1I5RfOE35ReoHZ8iIPEUAjNYRNTg55DCNw/pISD8VqJbK29i9e2qH5PTvJGVdQxLVvmcNQNP6UUDMQ7x53ESpdZNeVQ0KNoNrBzf+woACyxWCJ4=,iv:YUyNRQlMEFUW66W8fHb4fRFikTyufPpFwI85nymSrCE=,tag:dXRDZ/+onbCao/AyzlJjoA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
