apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:uGD9lAnz,iv:2Bm/mNBpogng1IaeTtICfo8u+eQdnBgJ8tLFOMFjDSI=,tag:8HALhqZYqmuXTw4o5GDW4A==,type:str]
  CLUSTER_ACME_EMAIL: ENC[AES256_GCM,data:GOUxzzLA85j+zQ9OOp+2bIPRpYrx,iv:PWxS8pcattCVkG89Y1hXTX57SKLIP4Qbvd8WsnMx1T4=,tag:Ue06rumCUK8/1h6t3Kx1pA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbkNmeDk3NzdDSlJWWnBY
        dzVMYkhIWURjamJzWXZhRTNvSnNNQjFaRms0CkUveWFRV3E0OWc0bUdOVDlqK2FK
        YjJpTVorUUxkRDMyRjdxZWl3bCtVWUUKLS0tIE9wK2JyS1o0OHcrajd4Q1Y4aEVp
        THd2V0tublNXeU9VbExJbkd2WkZMTVUKf5JdSFfM2A6S3Ty6t9MbR/rn0E98YYlo
        2POmryLIWUfb1SgrrBCfR39Di026ngiSgfY97aIv9BRLuGwQpiRcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8a4krypwu2xwdc8wgsmvpxru0dwaayk9njcevy9ddzw6kwvcaks7wzhv5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T11:31:31Z"
  mac: ENC[AES256_GCM,data:+2w5Wwx1b5YG+yNOW99fF3G0RHscSeb6cOPht1Xj6RchA+F8DJXIEyzhVTw20RlDyLuaThGJKH6sGC5BPJGstmBa7lIxvJBXMF+V15CXS2oyag6WTaDDd2EaCL4WtCPCZneU1p0rekFxgT4bsX6PsLzI9s4CduSuerNUaYYcxWY=,iv:D/XB2SwtgaoGpnFlzra4xyXU4UdupyzMa/WlHznqsJ4=,tag:r6+NRElEzlxXpl39+4FrEg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
