apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
stringData:
  CLUSTER_ACME_EMAIL: ENC[AES256_GCM,data:x7AJfV0g+ga8VWU1XVBQPyMFn5bk,iv:5S6tTDKnt6hxyVM+n69Y/cTe81DOCK+5HPnK7xo3S38=,tag:j1Yx6oOOHZdHNMliL9r3bA==,type:str]
  DOMAIN_IO: ENC[AES256_GCM,data:GXxX79wd,iv:bTzFqNr1jlfa9BNtbQtDl8wVKLx6cIsTOghgpECCH+s=,tag:IQ79eJI3DRxNPE8LlqF6HQ==,type:str]
  DOMAIN_APP: ENC[AES256_GCM,data:IAORIWjRFA==,iv:oqWe4zGivU1Vs3H2fJ9iYl/IwgWM1BsgjSmIF7i1Cyo=,tag:C9JpTo8hIs07s+NMygvwOA==,type:str]
  DOMAIN_CASA: ENC[AES256_GCM,data:J+zWC8x5Ygo=,iv:2C2YsNljix9dRNkVEheiDD+i6rgWIy7cqe6MFTIlfW0=,tag:jvkHwK8DZDyTj+aMIA43wQ==,type:str]
  DOMAIN_PROXII: ENC[AES256_GCM,data:MOfJWlQPP6GJ,iv:RUmQg4Q4wYgo6fp2xVp5Ag2+EYiRac9Pp8+gIhECfRQ=,tag:SJdbaE+QC8v7oFyXvMLB3w==,type:str]
  #ENC[AES256_GCM,data:+y5ZPBomxo8kiJ8JtaAmq18iHmHY55PEwhju2LgZYg8JhffYUDWEsx5H3TcsTgtKa2Y=,iv:JpsZ2sAKu52YzwR3YCVYerFs2kphHbSHivauXnGgpZM=,tag:A39AUWqXBCM8K44uRXD7Sg==,type:comment]
  DOMAIN_CLUSTER: ENC[AES256_GCM,data:GIylcRCv/QWI3a87gEI=,iv:dE/dcDSaThviqs85pRFMQTi2WxeEeXRgS2hWpEiV/nE=,tag:mXgTrUkYFo7i2VxfwqHM+Q==,type:str]
  #ENC[AES256_GCM,data:3I45H3tTj8syLVmNzMTl7Ci+IwdJ9r4m9Y7xx4P1,iv:w+uTzkeRiK3sWspQ2LmFnm9tu+n97vqEqk8MYE6eHWo=,tag:1rMDHhzz3CFw4fzhdrRMAQ==,type:comment]
  DOMAIN_APPS: ENC[AES256_GCM,data:1z5qaTh7cWWQPVI=,iv:L2hDkus9IK7uroR34/wquwF6yAWVGJR4L0ggjYFDBMg=,tag:+fmmED4XmAPeSyfZIUecgA==,type:str]
  DOMAIN_TAILSCALE: ENC[AES256_GCM,data:doeJ5hSdrYDbjx/E7u7N,iv:Z+smoQA+CyXBd1OlQLvMNwtu04dLQ1zj6m/G61maUlY=,tag:y0rHJMh+XDwWEH6i0MujYg==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0s7O0e0sw+loGl6UC+j61u+Qj2I8K9C58Q7HORGUq5vKfI4C,iv:OjyChuIbbyaXE6kNYWSyCKZie5PNlPF89N06vSHhFTU=,tag:3CTIfZCJXNa8h/SKnFH9FQ==,type:str]
  PG_HOST: ENC[AES256_GCM,data:WONeWfP3THdAoSX4zw59udfBGNRLvy+oBucM8q4BM9tZNxvc6ooIalLm,iv:13ab0CIbSLDS/nkplhffyZ3s9tmr7+Fy7Wliy+DCEFM=,tag:1mQc/7v0zGgCOHwVrlbqWA==,type:str]
  DRAGONFLY_HOST: ENC[AES256_GCM,data:IBv0wKbHOYlSHYky/zBqRfkWbw+1kMB99XAXNEg3IGR3TSXS,iv:/xGT++wERDODrScJah5ntapbZynzvLuVk7EI9Lg7ik4=,tag:9Be1fyuzTUGf2L6wY28LAA==,type:str]
  HOME_ASSISTANT_LAN_HOST: ENC[AES256_GCM,data:7et9B0+dnsQipw==,iv:3mkotTD2IiLHoe7Fawhrk0KY+XD11F/ITwYgx0facJE=,tag:upij+Ze0pNn4gbKS6p7j3A==,type:str]
  HOME_ASSISTANT_IOT_HOST: ENC[AES256_GCM,data:fIpiDPQom83pgw==,iv:JpoVjSeiWNpm4u6frsbvGEl6aB6GIgl28qjUhYckWac=,tag:gBz51jaZFIBVYvoKtOv43g==,type:str]
  NAS_HOST: ENC[AES256_GCM,data:42I44i7dTQsCZgI=,iv:Yvi9TTS1V3gxSQ0F5MPUGiiRpefJdZurWuh9cy083L4=,tag:oSyCpw/sAqtaKVXFqoPEnw==,type:str]
  NAS_LAN_HOST: ENC[AES256_GCM,data:naOETEVYo76Bqw==,iv:vdhOuF53yrovRjsUolgYxcBwYE3lzw3tHKJ2CVCEs9w=,tag:PLAwfLhZrVoCliswl4B4ew==,type:str]
  ADAM_IOT_HOST: ENC[AES256_GCM,data:Pe0fpy5OzksvUg==,iv:Z+Zwb9iFnLjy69qMUEgQi5yYJhSGkyYNzYG5z1ulyk4=,tag:hK8XGf1+l9JdD8SA0/H0jQ==,type:str]
  ANNA_IOT_HOST: ENC[AES256_GCM,data:dqHHSTAnGhsX8A==,iv:HImjeGk1zaWc2pVld6jRjBdS/1jm/vvtPqwUcneQP3Y=,tag:/WuSw6jFXZP8ZMZhev8sdA==,type:str]
  PRINTER_IOT_HOST: ENC[AES256_GCM,data:Rg1GOByOZUrLwQ==,iv:3xOm9dRWEM6z3EHTEfDMIbseSkdouVFPNhlimSUY8hQ=,tag:qD+CntUSWEq1EnlACJt3EQ==,type:str]
  WAN_FAILOVER_HOST: ENC[AES256_GCM,data:tAaBJ9R3kx1pq1g=,iv:jfcPTFZDKyMOu7s0UjXfHc60px5o3d7aYyREViJHZek=,tag:kXmdJXh2TIRSypXLwhKVLA==,type:str]
  LAN_SUBNET: ENC[AES256_GCM,data:jYCWJLYytgfoqvqY,iv:5X2TifXFd/tneDYyVy7B9WQexefzP27mIVNxCADiyHE=,tag:ORhUBDWxgOEVZw/mNZg8Zw==,type:str]
  IOT_SUBNET: ENC[AES256_GCM,data:z8kuvYaDToRRBp1Y,iv:Hnqn1pU1Eds/PDMD74N6bhdNDRTwh56RMO+Sok5qc74=,tag:9+rafDvLW2RWQPcX4BA/gw==,type:str]
  #ENC[AES256_GCM,data:yzvV1vErlcovmKD0H/e8ZMEdDTws+0Wzxb6cj5rSD2M1MjkbnNSKB8ErnYLOaCEyt4pH6LrT2q03MxODnUDUDVYJOBqxS0+/0PyRmKyAew==,iv:hwn6/uhmdDgHrNFNZIW8/oUla53UWwCFIJiVZdSGPMM=,tag:p6ifEETFkKh3hSKllnhBhg==,type:comment]
  #ENC[AES256_GCM,data:T1wyhhd+ZVdorS1ITjNfEj3Q9V0iXWFtuevDehGlsGAKNXI6732n/7uZAXOg9AhC9BcsvbY7rC58WkktXtykAJJV5jtFGiV6,iv:hn9wq/iuRTBGHiAeo5QsAFCD7/op/l7dJ09vYVyUM/k=,tag:8HVr42yPnenOwnF3zSOSTw==,type:comment]
  LAN_CIDR: ENC[AES256_GCM,data:yK+8fG+98CPi2eey,iv:jAKvCdsZ4ru0BJoDxBuGoG/BEMBx4DNp5x5CaPB1AuQ=,tag:Fb1qMCCXkMW7YVUMzN/opA==,type:str]
  POD_CIDR: ENC[AES256_GCM,data:+ApzoShZn+OeFQJp,iv:jJY+NsQNbysGEh4jTq8wiLpfL/0xRXmyx5yDmmwru0I=,tag:kigxIhA4We5NycrSbt8Tkg==,type:str]
  SERVICE_CIDR: ENC[AES256_GCM,data:boFcSRrMMlSwJKTa,iv:jA6Rj3kbJ/rreSkeCzd7gkJgz6ZTG2BPpmqMXfHPjlU=,tag:f5oSgOQDI+s7yj5cbiGuSw==,type:str]
  #ENC[AES256_GCM,data:oHY0Ui7A0URJ6lyk1oio/6afpQB1m6aGSI44Qn7XxkFsx0meB8DMX5AdKkVws8Oton1s59uVVxffxeL8bVZTRlG4exWy5vY28Q==,iv:kDSJMsMkYzSY+e2oZJfGJyLIiVTSIwdSHDtA0g0T1Sw=,tag:3JC9ahkhyH0gahvFuCrf5w==,type:comment]
  #ENC[AES256_GCM,data:ImdnstLR/tFwYz3GkDxdZ7Pb7j1JNKD8P8xtcnoVbryQt4gBrDVE4jlgHX0M77tdIMnHkl93S2suxA==,iv:nfQ/Yr74+wEfzUYv0+fj4SWOsrPae8l81EJpvd/jq9M=,tag:rt3KFFUFZ0HHQUAvnVkr0w==,type:comment]
  TAILSCALE_CIDR: ENC[AES256_GCM,data:CEswu9xlw3dEIOCZuQ==,iv:tsgJfzcuGmq+VOpU0YFSrEFn9RmOcPvm8nxYWZPkE68=,tag:kMKGE9xIeNP+3Uudtq66hg==,type:str]
  #ENC[AES256_GCM,data:+GOKL3mv+eSL7/2X7wElpVMvGToDxSr4yR9+rH4F0aw9J0BnJghukmZe0yXJ4LPH7efbesgqV8Bbn+UHToxQg98h8wV+dHDen8rDWQ==,iv:1TS4c0li9ChFKPmXFbN5+9aIOQ4Qda5IjZWdEeRqIi0=,tag:WzRKO8s7DJoqDe4rQC6Qzw==,type:comment]
  #ENC[AES256_GCM,data:KMf+cdCkBeAhaWDLoaweF7Taf5qVrkMEzmKCtC/w5dZQkq/gHOmwxjmY7o8KkCwfuYCYhGYtklXLiubmfjJZx8d1t9w8W5FDCg==,iv:QTS8haak9StAXDpIVUdSv7LjxilF10B7+Drzr/oUqoQ=,tag:WsHQOBKqRdq3c0GkUwD3TQ==,type:comment]
  #ENC[AES256_GCM,data:xYADEhmWnYtZEKqJzTa0UxNHc4pjWdeZ+MBEF22OfwNWcnRAwF1y4C5ynGkj/Fnz5Ast,iv:N9qvP513ACnY65+orNpzfH4h5UP4CHwf0NYAGybuzgA=,tag:7N8/OAImLe3Lo5CVqTnrZg==,type:comment]
  LB_IP_PLEX: ENC[AES256_GCM,data:mbyf8aXbvnFo5n8=,iv:unZVGnxYRextcyeLnayFuv353/nLVm5G6sJj9oENpSo=,tag:EVo5xhZThVt0btIAltncXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MEVnVThxandqaVBGb1U5
        VlRVeHUvdElkbmtPaGtvNTltWGNxZVp3c25rCmR5VVIyTk9uQXE5TThiM3VuUHJj
        R0VJbE9HMmVVdmJ3OXJFOFJlYWJwcUkKLS0tIER6QWlmSEo1T0pMWUROQ1dzZDBL
        Rnc5SE5QK1BqZzJCM3BYVEZiVzRzZW8KDbymgDXc2wIuDF/DjseA9GFImfNKbi9N
        ugocY2qFdEHJrAFC0AagCcG4YAo/R8GtOjnhN/PB/ooGuV94ZwH5aQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8a4krypwu2xwdc8wgsmvpxru0dwaayk9njcevy9ddzw6kwvcaks7wzhv5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T10:45:19Z"
  mac: ENC[AES256_GCM,data:yrRdRGNDjcyGEDuADFcX3ySoskqt1bP0BwZOdC5Xp1xtrYH//IlZ1JDAYVIJvNcUpaAMGchEelC24sOeeTwbzt+6OnM7Y7VdUnPA1smaY/JW0pkcDCbF1/6I7VfU1UeSt1/bEHgfphDJ6uRkxq6rqDUzve80xYMSkytGceyU9VQ=,iv:LeOiry1nwJDy86qadDtm+g3gdDuIEqKEDoRpXRoEhCI=,tag:sGqh3q2anY/Xwiz6+sHGMA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
