---
# yaml-language-server: $schema=https://schemas.clustrs.dev/resource.k8s.io/resourceclaimtemplate_v1.json
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: ${APP}-gpu
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly:
            adminAccess: true
            allocationMode: All
            deviceClassName: gpu.intel.com
