---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: whereabouts-chart
  namespace: flux-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/k8snetworkplumbingwg/whereabouts-chart
  ref:
    # renovate: datasource=docker depName=ghcr.io/k8snetworkplumbingwg/whereabouts-chart
    tag: "0.9.3"
