---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-secret
    template:
      data:
        PLEX_CLAIM_TOKEN: "{{ .PLEX_CLAIM_TOKEN }}"
      engineVersion: v2
  dataFrom:
    - extract:
        key: plex
      rewrite:
        - regexp:
            source: (.*)
            target: PLEX_$1
