---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: plex
  interval: 1h
  driftDetection:
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: "${APP}-gpu"
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.43.4.10903@sha256:fdc6fe82bc7d8acd08fc0aa581fcb76722803ba5905e2537135a697347dd6149
            env:
              PLEX_ADVERTISE_URL: "https://plex.${DOMAIN_APP}:443,https://plex.${DOMAIN_CLUSTER}:443,http://${LB_IP_PLEX}:32400,http://${LB_IP_PLEX_IOT}:32400,https://${APP_SUBDOMAIN:=${APP}}.${DOMAIN_TAILSCALE}:443,http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:32400"
              PLEX_NO_AUTH_NETWORKS: "${LAN_CIDR},${POD_CIDR},${SERVICE_CIDR},${TAILSCALE_CIDR}"
              PLEX_PREFERENCE_1: "AllowMediaDeletion=0"
              PLEX_PREFERENCE_2: "EnableIPv6=0"
              PLEX_PREFERENCE_3: "FriendlyName=SkyNet Plex"
              PLEX_PREFERENCE_4: "LanNetworksBandwidth=${LAN_CIDR}"
              PLEX_PREFERENCE_5: "ButlerDatabaseBackupPath=/mnt/backups"
              PLEX_PREFERENCE_6: "RelayEnabled=0"
              PLEX_PREFERENCE_7: "sendCrashReports=0"
              PLEX_PREFERENCE_8: "secureConnections=1"
              TZ: "${CLUSTER_TIMEZONE}"
            envFrom:
              - secretRef:
                  name: plex-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 20m
                memory: 2Gi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
    ingress:
      ts:
        annotations:
          tailscale.com/tags: "tag:plex"
        className: tailscale
        hosts:
          - host: &host ${APP_SUBDOMAIN:=${APP}}.${DOMAIN_TAILSCALE}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: "${KOPIUR_CLAIM:=${APP}}"
        globalMounts:
          - path: /config
      media:
        type: nfs
        path: /mnt/tank/Media
        server: "${NAS_HOST}"
        globalMounts:
          - path: /mnt/media
      backups:
        type: nfs
        path: /mnt/tank/Cluster/backup
        server: "${NAS_HOST}"
        globalMounts:
          - path: /mnt/backups
            subPath: apps/plex
      scratch:
        type: emptyDir
        sizeLimit: 20Gi
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
                subPath: logs
              - path: /transcode
                subPath: transcode
              - path: /tmp
                subPath: tmp
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${LB_IP_PLEX},${LB_IP_PLEX_IOT}"
        controller: plex
        ports:
          http:
            port: *port
