---
# yaml-language-server: $schema=https://schemas.clustrs.dev/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: home-assistant
spec:
  endpoints:
    - ip:
        address: "${HOME_ASSISTANT_LAN_HOST}"
        port: 8123
