---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/http.keda.sh/interceptorroute_v1beta1.json
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: pgadmin
spec:
  target:
    service: pgadmin
    port: 5050
  rules:
    - hosts:
        - "pgadmin.${DOMAIN_CLUSTER}"
  scalingMetric:
    concurrency:
      targetValue: 1
