---
# yaml-language-server: $schema=https://schemas.clustrs.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: bond-storage-degraded-x520-fallback-ceph
spec:
  matchers:
    - name: alertname
      value: CephNodeNetworkBondDegraded
    - name: master
      value: bond-storage
