---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-lab
spec:
  chartRef:
    kind: OCIRepository
    name: home-lab
  interval: 1h
  values:
    containerMode:
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: openebs-hostpath
      type: kubernetes
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    githubConfigSecret: home-lab-runner-secret
    githubConfigUrl: "https://github.com/qnimbus/home-lab"
    maxRunners: 6
    minRunners: 0
    template:
      spec:
        containers:
          - command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            image: ghcr.io/home-operations/actions-runner:2.337.0
            name: runner
            volumeMounts:
              - mountPath: /var/run/secrets/talos.dev
                name: talos
                readOnly: true
        serviceAccountName: actions-runner
        volumes:
          - name: talos
            secret:
              secretName: home-lab
