---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-unifi-secret
  data:
    - secretKey: UNIFI_HOST
      remoteRef:
        key: unifi
        property: UNIFI_HOST
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: unifi
        property: UNIFI_API_KEY
