---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: canon
  annotations:
    external-dns.kubernetes.io/hostname: "canon.iot.${DOMAIN_IO}"
spec:
  externalName: "${PRINTER_IOT_HOST}"
  type: ExternalName
