---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-ngx
spec:
  targetNamespace: default
  components:
    - ../../../../components/dragonfly
    - ../../../../components/kopiur/backup
    - ../../../../components/postgres
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: csi-driver-smb
      namespace: system
  interval: 1h
  path: ./kubernetes/apps/default/paperless-ngx/app
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CLAIM: paperless-ngx-config
      POSTGRES_BACKUP_SCHEDULE: "0 7 3 * * *"
      POSTGRES_DATABASE: paperless
      POSTGRES_USERNAME: paperless
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: default
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      current: status.phase == 'Ready'
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
