---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smtp-relay-secret
    template:
      data:
        SMTP_RELAY_SERVER: "{{ .RELAYHOST_HOST }}"
        SMTP_RELAY_SERVER_PORT: "{{ .RELAYHOST_PORT }}"
        SMTP_RELAY_USERNAME: "{{ .RELAYHOST_USERNAME }}"
        SMTP_RELAY_PASSWORD: "{{ .RELAYHOST_PASSWORD }}"
  dataFrom:
    - extract:
        key: smtp-relay
      rewrite:
        - regexp:
            source: (.*)
            target: RELAYHOST_$1
