---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_ADMIN_MAIL: "{{ .PAPERLESS_ADMIN_MAIL }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
      engineVersion: v2
  dataFrom:
    - extract:
        key: paperless
      rewrite:
        - regexp:
            source: (.*)
            target: PAPERLESS_$1
