---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
components:
  - ../../components/namespace
resources:
  - ./crd-schema-publisher/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./csi-driver-smb/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./keda/ks.yaml
  - ./kopiur/ks.yaml
  - ./openebs/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
