---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/namespace
namespace: actions-runner-system
replacements:
  - path: ../../components/replacements/replacements.yaml
resources:
  - ./actions-runner-controller/ks.yaml
