---
# yaml-language-server: $schema=https://schemas.clustrs.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudnative-pg-rules
spec:
  groups:
    - name: cloudnative-pg.rules
      rules:
        - alert: LongRunningTransaction
          expr: cnpg_backends_max_tx_duration_seconds > 300
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: A transaction on {{ $labels.namespace }}/{{ $labels.pod }} has been running for more than 5 minutes.
        - alert: BackendsWaiting
          expr: cnpg_backends_waiting_total > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "{{ $value }} backends on {{ $labels.namespace }}/{{ $labels.pod }} have been waiting for locks for 5 minutes."
        - alert: PGDatabase
          expr: cnpg_pg_database_xid_age > 300000000
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Database {{ $labels.datname }} on {{ $labels.namespace }}/{{ $labels.pod }} is approaching transaction ID wraparound.
        - alert: PGReplication
          expr: cnpg_pg_replication_lag > 300
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Standby {{ $labels.namespace }}/{{ $labels.pod }} is more than 5 minutes behind the primary.
        - alert: LastFailedArchiveTime
          expr: (cnpg_pg_stat_archiver_last_failed_time - cnpg_pg_stat_archiver_last_archived_time) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: WAL archiving is failing on {{ $labels.namespace }}/{{ $labels.pod }}; the last failure is more recent than the last success.
        - alert: DatabaseDeadlockConflicts
          expr: increase(cnpg_pg_stat_database_deadlocks[10m]) > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Database {{ $labels.datname }} on {{ $labels.namespace }}/{{ $labels.pod }} had more than 10 deadlocks in 10 minutes.
        - alert: ReplicaFailingReplication
          expr: cnpg_pg_replication_in_recovery > cnpg_pg_replication_is_wal_receiver_up
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Replica {{ $labels.namespace }}/{{ $labels.pod }} is in recovery but its WAL receiver is down.
