---
# yaml-language-server: $schema=https://schemas.clustrs.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nas-kopia-ui
  annotations:
    gethomepage.dev/description: "Backup repository browser (read-only)"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "kopia"
    gethomepage.dev/name: "Kopia"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=kopiur-server,app.kubernetes.io/instance=nas"
spec:
  hostnames:
    - "kopia.${DOMAIN_CLUSTER}"
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: nas-kopia-ui
          port: 51515
