---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nas-kopia-ui
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Kopia"
    gethomepage.dev/description: "Backup repository browser (read-only)"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "kopia"
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - "kopia.${DOMAIN_CLUSTER}"
  rules:
    # Service created by kopiur from the ClusterRepository's spec.server.
    - backendRefs:
        - name: nas-kopia-ui
          port: 51515
