---
# Apply targetNamespace to all Flux Kustomizations
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        labelSelector: replacements.flux.home.arpa/disabled notin (true)
      fieldPaths:
        - metadata.namespace
      options:
        create: true
    - select:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        labelSelector: replacements.flux.home.arpa/disabled notin (true)
      fieldPaths:
        - spec.targetNamespace
      options:
        create: true
