---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./ai
  - ./cert-manager
  - ./external-secrets
  - ./flux-system
  - ./kube-system
  - ./mail
  - ./network
  - ./openebs
  - ./observability
  - ./system-upgrade
  - ./actions-runner-system
  - ./system
  - ./rook-ceph
  - ./automation
  - ./database
  - ./default
  - ./documents
  - ./finance
  - ./node-feature-discovery
  - ./intel-device-plugins
  - ./media
  - ./downloads
