---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Add app namespaces here as you create them, e.g.:
# resources:
#   - ./kube-system
#   - ./cert-manager
#   - ./flux-system
