---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .CF_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .CF_API_TOKEN }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .CF_TUNNEL_ID }}"
        HOMEPAGE_VAR_HOMEASSISTANT_TOKEN: "{{ .HP_HOMEASSISTANT_TOKEN }}"
        HOMEPAGE_VAR_KAGI_SESSION_TOKEN: "{{ .HP_KAGI_SESSION_TOKEN }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .HP_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .HP_LONGITUDE }}"
        HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY: "{{ .HP_OPENWEATHERMAP_API_KEY }}"
        HOMEPAGE_VAR_TRUENAS_API_KEY: "{{ .HP_TRUENAS_API_KEY }}"
        HOMEPAGE_VAR_UNIFI_API_KEY: "{{ .HP_UNIFI_API_KEY }}"
  dataFrom:
    - extract:
        key: homepage
      rewrite: [{regexp: {source: (.*), target: HP_$1}}]
    - extract:
        key: cloudflared
      rewrite: [{regexp: {source: (.*), target: CF_$1}}]
