---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_MCP_TOKEN: "{{ .HOMEPAGE_MCP_TOKEN }}"
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .CF_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .CF_API_TOKEN }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .CF_TUNNEL_ID }}"
        HOMEPAGE_VAR_HOMEASSISTANT_TOKEN: "{{ .HOMEPAGE_HOMEASSISTANT_TOKEN }}"
        HOMEPAGE_VAR_KAGI_SESSION_TOKEN: "{{ .HOMEPAGE_KAGI_SESSION_TOKEN }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .HOMEPAGE_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .HOMEPAGE_LONGITUDE }}"
        HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY: "{{ .HOMEPAGE_OPENWEATHERMAP_API_KEY }}"
        HOMEPAGE_VAR_TRUENAS_API_KEY: "{{ .HOMEPAGE_TRUENAS_API_KEY }}"
        HOMEPAGE_VAR_UNIFI_API_KEY: "{{ .HOMEPAGE_UNIFI_API_KEY }}"
  dataFrom:
    - extract:
        key: homepage
      rewrite:
        - regexp:
            source: (.*)
            target: HOMEPAGE_$1
    - extract:
        key: cloudflare-tunnel
      rewrite:
        - regexp:
            source: (.*)
            target: CF_$1
