---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./config/settings.yaml
      - ./config/kubernetes.yaml
      - ./config/widgets.yaml
      - ./config/services.yaml
      - ./config/bookmarks.yaml
      - ./config/docker.yaml
      - ./config/proxmox.yaml
      - ./config/custom.css
      - ./config/custom.js
    name: homepage-config
    options:
      disableNameSuffixHash: true
resources:
  - ./externalsecret.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
