---
# yaml-language-server: $schema=https://schemas.clustrs.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-importer
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: firefly-importer-secret
    template:
      data:
        FIREFLY_III_ACCESS_TOKEN: "{{ .FIREFLY_ACCESS_TOKEN }}"
      engineVersion: v2
  dataFrom:
    - extract:
        key: firefly-III
      rewrite:
        - regexp:
            source: (.*)
            target: FIREFLY_$1
