---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-importer
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: firefly-importer
  driftDetection:
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    controllers:
      firefly-importer:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/fireflyiii/data-importer
              tag: version-2.3.4@sha256:26459e1f014544f1ae56d1beed9c6a0ddf208b1eaa24cf11fa77ebd1f51422c8
            env:
              FIREFLY_III_URL: "http://firefly.default.svc.cluster.local:8080"
              TRUSTED_PROXIES: "**"
              VANITY_URL: "https://firefly.${DOMAIN_CLUSTER}"
            envFrom:
              - secretRef:
                  name: firefly-importer-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 10
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      app:
        ports:
          http:
            port: *port
