---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: firefly
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 33
        runAsUser: 33
    controllers:
      firefly:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/fireflyiii/core
              tag: version-6.6.6@sha256:ae69fdd95cdef9038cd7a460a5aec731f14813973e4f096511d5a4ea9ff0e972
            env:
              APP_DEBUG: "false"
              APP_ENV: production
              APP_URL: "https://firefly.${DOMAIN_CLUSTER}"
              DB_CONNECTION: pgsql
              DB_DATABASE: firefly
              DB_HOST: "${APP}-postgres-rw"
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: firefly-postgres-app
              DB_PORT: "5432"
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: firefly-postgres-app
              TRUSTED_PROXIES: "**"
              TZ: ${CLUSTER_TIMEZONE}
            envFrom:
              - secretRef:
                  name: firefly-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 60
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    persistence:
      upload:
        existingClaim: "${KOPIUR_CLAIM:=${APP}}"
        globalMounts:
          - path: /var/www/html/storage/upload
    service:
      app:
        ports:
          http:
            port: *port
