---
config:
  modules:
    http_2xx:
      http:
        follow_redirects: true
        preferred_ip_protocol: "ip4"
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      prober: http
      timeout: 5s
    icmp:
      icmp:
        preferred_ip_protocol: "ip4"
      prober: icmp
      timeout: 5s
    smtp_banner:
      prober: tcp
      tcp:
        preferred_ip_protocol: "ip4"
        query_response:
          - expect: "^220 "
          - send: "QUIT\r"
          - expect: "^221 "
      timeout: 5s
    tcp_connect:
      prober: tcp
      tcp:
        preferred_ip_protocol: "ip4"

      timeout: 5s
fullnameOverride: blackbox-exporter

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
serviceMonitor:
  enabled: false
  selfMonitor:
    enabled: true
    interval: 60s
    scrapeTimeout: 30s
