---
# yaml-language-server: $schema=https://schemas.clustrs.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
  interval: 1h
  releaseName: ceph-csi-drivers
  dependsOn:
    - name: rook-ceph-operator
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Driver|OperatorConfig|ServiceAccount|ClusterRole|ClusterRoleBinding|Role|RoleBinding
            patch: |
              - op: add
                path: /metadata/annotations
                value:
                  helm.sh/resource-policy: keep
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        clusterName: rook-ceph
        nodePlugin:
          priorityClassName: system-node-critical
          resources:
            plugin:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 1Gi
            registrar:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
        controllerPlugin:
          priorityClassName: system-cluster-critical
          resources:
            plugin:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
            provisioner: &sidecar
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            attacher: *sidecar
            resizer: *sidecar
            snapshotter: *sidecar
    drivers:
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeSnapshot
        grpcTimeout: 150
        log:
          rotation:
            enabled: false
        controllerPlugin:
          replicas: 2
          hostNetwork: false
      cephfs:
        enabled: false
      nfs:
        enabled: false
      nvmeof:
        enabled: false
