---
# yaml-language-server: $schema=https://schemas.clustrs.dev/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${APP}
spec:
  cooldownPeriod: 1800
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: ${APP}
  triggers:
    - type: external-push
      metadata:
        interceptorRoute: ${APP}
        scalerAddress: keda-add-ons-http-external-scaler.system:9090
