---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cilium.io/ciliumbgpclusterconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-cluster-config
spec:
  bgpInstances:
    - name: cilium
      localASN: 64514
      peers:
        - name: udm
          peerAddress: 10.60.0.1
          peerASN: 64513
          peerConfigRef:
            name: bgp-peer-config
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cilium.io/ciliumbgppeerconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: bgp-peer-config
spec:
  families:
    - advertisements:
        matchLabels:
          advertise: bgp
      afi: ipv4
      safi: unicast
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/cilium.io/ciliumbgpadvertisement_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisement
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      selector:
        matchExpressions:
          - { key: "io.kubernetes.service.namespace", operator: NotIn, values: ["mail", "media"] }
      service:
        addresses:
          - LoadBalancerIP
