---
# yaml-language-server: $schema=https://schemas.clustrs.dev/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: kube-api
  annotations:
    external-dns.kubernetes.io/hostname: kube-vip.cluster.vwn.io
    lbipam.cilium.io/ips: "10.60.0.2"
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  type: LoadBalancer
