---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
spec:
  targetNamespace: media
  components:
    - ../../../../components/gpu
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: intel-gpu-resource-driver
      namespace: system
  interval: 1h
  path: ./kubernetes/apps/media/plex/app
  postBuild:
    substitute:
      APP: *app
      APP_SUBDOMAIN: *app
      KOPIUR_CACHE_CAPACITY: 20Gi
      KOPIUR_CAPACITY: 20Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: media
---
# yaml-language-server: $schema=https://schemas.clustrs.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex-tools
spec:
  targetNamespace: media
  interval: 1h
  path: ./kubernetes/apps/media/plex/tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: plex-image-cleanup
      namespace: media
