---
# This file is not managed by doco-cd because it can't manage itself

secrets:
  op_token:
    file: /home/truenas_admin/.config/doco-cd/op_token
  api_secret:
    file: /home/truenas_admin/.config/doco-cd/api_secret
  webhook_secret:
    file: /home/truenas_admin/.config/doco-cd/webhook_secret
services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.125.1@sha256:38198abbda1b55da7a7f37a7924b2ccdcc0583bd24466b7c2103ef6cd2ffc828
    restart: unless-stopped
    environment:
      API_SECRET_FILE: /run/secrets/api_secret
      DEPLOY_CONFIG_BASE_DIR: ./docker/nas/
      HTTP_PORT: 8880
      LOG_LEVEL: info
      POLL_CONFIG: |
        - url: https://github.com/qnimbus/home-lab.git
          reference: refs/heads/main
          interval: 3600
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/op_token
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      TZ: Europe/Amsterdam
    ports:
      - 8880:8880
      - 9120:9120
    secrets:
      - op_token
      - api_secret
      - webhook_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: {}
