---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.networking.k8s.io/referencegrant_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: pgadmin-httproute-to-interceptor
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: database
  to:
    - group: ""
      kind: Service
      name: keda-add-ons-http-interceptor-proxy
